### ISSUE TITLE
Consider simple character vector for the stack trace

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#107]
When I test:

```r
task <- mirai::mirai(f(123), f = function(x) g(x), g = function(x) stop(x))
```

I see:

```r
> str(attributes(task$data)$stack.trace)
List of 4
 $ : language stop(x)
  ..- attr(*, "srcref")= 'srcref' int [1:8] 1 56 1 74 56 74 1 1
  .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x1262d7e08> 
 $ : language g(x)
  ..- attr(*, "srcref")= 'srcref' int [1:8] 1 34 1 49 34 49 1 1
  .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x1262d7e08> 
 $ : language f(123)
 $ : language eval(expr = ._mirai_.[[".expr"]], envir = ._mirai_., enclos = NULL)
```

If I recall correctly, language objects in the stack trace have environments which could ship large global data objects accidentally. This could slow down the reporting of errored tasks. Would it be possible to deparse the stack trace to a simple character vector before sending it back?

**Comment by shikokuchuo** [comment]
I could, but the stack trace would become much less rich. If there is a danger of sending back very large srcfile environments then I can do this as an interim measure, and then see how much is safe to add back.

**Comment by shikokuchuo** [comment]
The deparsed stack trace is now returned in [564de21](https://github.com/shikokuchuo/mirai/commit/564de210bf2c6dc2e1810d0772815db19eb222a9).

**Comment by wlandau** [comment]
> The deparsed stack trace is now returned in [564de21](https://github.com/shikokuchuo/mirai/commit/564de210bf2c6dc2e1810d0772815db19eb222a9).

Thanks!

> the stack trace would become much less rich

Is srcfile/srcref information necessary for non-interactive workflows? `browser()` and `options(error = recover)` may use it, but these don't seem to apply here.

> If there is a danger of sending back very large srcfile environments then I can do this as an interim measure, and then see how much is safe to add back.

If you do end up adding back scrfile/srcref information, it would be great to be able to have the option to disable the stack trace entirely. `crew` and `targets` each get their own deparsed stack traces.

**Comment by shikokuchuo** [comment]
> Is srcfile/srcref information necessary for non-interactive workflows? browser() and options(error = recover) may use it, but these don't seem to apply here.

The print method for srcref is quite involved. If you compare how Sys.calls() prints, vs the simple deparsed version, the context of each call is lost.

> If you do end up adding back scrfile/srcref information, it would be great to be able to have the option to disable the stack trace entirely. `crew` and `targets` each get their own deparsed stack traces.

`crew` uses an inner evaluation wrapper, so it should never cause mirai to add its own stack trace on top.

**Comment by shikokuchuo** [comment]
> The print method for srcref is quite involved. If you compare how Sys.calls() prints, vs the simple deparsed version, the context of each call is lost.
> 
This turned out easier than expected. [1cac9a1](https://github.com/shikokuchuo/mirai/commit/1cac9a1450f122ae87f380089c285cdd48d9b05b)

**Comment by HenrikBengtsson** [comment]
Just adding https://github.com/HenrikBengtsson/Wishlist-for-R/issues/86 (WISH: Support for modifying base::.Traceback) since it's related to this feature.
