### ISSUE TITLE
Question about mirai vs callr

### ISSUE THREAD

**Issue by ekianjo** [shikokuchuo/mirai#11]
Hi, I'd like to know the following:

- is mirai any different from callr, or do they roughly do something similar under the hood? 
- are there advantages in using mirai vs callr? 

thanks for your help

**Comment by shikokuchuo** [comment]
I think to the user possibly similar. Under the hood, the implementation will be significantly different.

'callr' has many other bells and whistles that probably make it slower and provide potential points of failure. 'mirai' is designed to be simple and rock solid. If mirai has the features you need, I would go with the simpler design.

'mirai' also has only one dependency ('nanonext') and no recursive dependencies. 'nanonext' is a highly-optimised package that is written in C where possible to wring out the most performance, and wraps the NNG C library, which is a best-in-class messaging library (re-write of ZeroMQ).

Hope the above is helpful. I'd love to hear your thoughts - let me know if you find either better for your needs.

**Comment by ekianjo** [comment]
thank you @shikokuchuo ! You might want to include that kind of comments in the documentation as I am sure I am not the online one who thought about callr when looking at mirai. 

One more thing. When you pass an expression to mirai, does it need to be pure R code? can mirai use any of the loaded libraries or data objects when creating a new session? Or should I assume that all mirai is a pristine, independent environment?

**Comment by ekianjo** [comment]
Sorry one more comment on this - since you can pass long expressions within a call_mirai function, I guess it could be possible to pass a whole script if you really wanted to. Would it be possible for you to create a function where a call_mirai() like function could take a "script.R" file as an argument? That would make it very practical to use to run existing scripts without modification.

**Comment by shikokuchuo** [comment]
@ekianjo mirai is not at all limited in what can be evaluated. Everything is covered in the readme / documentation (which also contains examples that can be run).

You can use `mirai(tibble::tibble())` or `mirai({library(tibble); tibble()})`
You can put any valid R expression in `mirai({   })`.

You pass variables as additional arguments to `mirai()` or using either the `...` or `.args` interface. So e.g. 
```
r <- mirai(m * rnorm(n), n = 1e7, m = 100)
```

or
```
n <- 1e7
m <- 100
r <- mirai(m * rnorm(n), .args = list(m, n))
```

If you want to execute a script it is as simple as `mirai(source("filename"))`.

Did you solve your issue in the end? Please post your source code if something isn't behaving as documented. Thanks.

**Comment by ekianjo** [comment]
Thanks, yeah I was able to figure most things out before your message! But your point that you could use a source statement inside mirai was very helpful!
