### ISSUE TITLE
Example not working for me: shiny generative art

### ISSUE THREAD

**Issue by dcaud** [shikokuchuo/mirai#114]
Package looks helpful! The following shiny code never produces plots for me: https://shikokuchuo.net/mirai/articles/shiny.html#shiny-extendedtask-example-generative-art

**Comment by shikokuchuo** [comment]
Apologies, I'm working on the next release of `mirai` and that example was updated too early and makes use of a new feature (i.e. being able to pass in an environment), currently in the dev version. The example has been updated so it works with the current release. Using the `...` to pass in variables from the `ExtendedTask$invoke` method is actually a good pattern for use of `mirai` with Shiny.
