### ISSUE TITLE
mirai vs callr performance: a simple test

### ISSUE THREAD

**Issue by ekianjo** [shikokuchuo/mirai#12]
Here is a simple test to confirm that mirai is much faster than callr, to produce the exact same results.

```
library(mirai)
library(tictoc)
library(tidyverse)
library(callr)

# example with mirai

tic("Process with mirai- Duration: ")

mirai <- list()
for (i in 1:2) {
mirai[[i]] <- eval_mirai(
  
  {
    library(tidyverse)
    big_calculation <- function() {
      
      rnorm(1e8) %>%  tibble::as_tibble() %>% return()
    }
  big_calculation()}
  
  )
}

while(unresolved(mirai[[1]]) | unresolved(mirai[[2]])) {
}

toc()

# example with callr

# callr does not allow for library calls in its functions, except when using :: so we need to rewrite the function here.

big_calculation_callr <- function() {
  
  magrittr::`%>%`(magrittr::`%>%`(rnorm(1e8),tibble::as_tibble()),return())
}


tic("Process with callr- Duration: ")
callr_list <- list()
for (i in 1:2) {
callr_list[[i]] <- callr::r_bg(big_calculation_callr)
}

while(is.null(callr_list[[1]]$get_exit_status()) |  is.null(callr_list[[2]]$get_exit_status())) {
}
toc()
```

The results speak for themselves:

Process with mirai- Duration: : 17.798 sec elapsed
Process with callr- Duration: : 66.705 sec elapsed

**Comment by shikokuchuo** [comment]
I guess I can't complain as mirai comes out so far ahead, but it hardly seems fair given the mirai call loads the entire tidyverse wheras callr does not.

A more classic benchmark would probably do a minimal call in both to measure just the pure overhead, but as there is such a large difference in your 'big calculation' perhaps mirai manages memory better (makes fewer copies) - if data is being swapped from memory to disk in the callr process that might account for the difference (pure speculation).
