### ISSUE TITLE
Working with Shiny: How to Make Mirai work with ObserveEvent ?

### ISSUE THREAD

**Issue by ekianjo** [shikokuchuo/mirai#13]
hi @shikokuchuo 
I am trying to make mirai work inside a Shiny application. SO far so good when it comes to running a mirai subprocess, however I am having issues to "detect" when the mirai process is actually finished with an observeEvent. 

To make things simple I am doing the following:

reactive_values$mirai_process_val <- eval_mirai(<script>)

and in the server part of Shiny:

observeEvent(reactive_values$mirai_process_val, {if (!unresolved(reactive_values$mirai_process_val){<series_of_actions>}})

What works:
- when the mirai process starts, the reactive value is changed as expected, and I can see the ObserveEvent working to check for the unresolved value.
- However, it seems that when the mirai process is resolved, there does not seem to be a signal coming back that is picked up by the ObserveEvent. 

My guess is that there is only the  $data part of the mirai object that is updated, and therefore it is not being picked up as a new value by ObserveEvent. 

Any suggestion on how to resolve this?

**Comment by shikokuchuo** [comment]
The mirai polls for completion each time you access $data (it is an active binding) or use unresolved(). So I think the answer you are looking for is to condition the observeEvent on another action such as mouse click or hover etc. that will cause unresolved() to run in your case as otherwise it will not run by itself.

**Comment by ekianjo** [comment]
Thanks, very clear. I ended up doing a process that watches for the completion and takes action when mirai is resolved. I have found a different issue though, will create a different topic. You can close this one.

**Comment by shikokuchuo** [comment]
It is now possible to use `mirai` with Shiny through the {crew} package https://cran.r-project.org/package=crew. This vignette shows the way: https://wlandau.github.io/crew/articles/shiny.html
