### ISSUE TITLE
[Question] Can mirai be responsible for an error for the creation of a server socket?

### ISSUE THREAD

**Issue by mooibroekd** [shikokuchuo/mirai#146]
Hi,

I am using a package that uses mirai by setting up parallel processing. I got the following error:

```
Error: Error in serverSocket(port = port): creation of server socket failed: port 11692 cannot be opened
```
From what I have found it could be related to `parallel::makeCluster(no_clusters)` from what I have found on [SO](https://stackoverflow.com/questions/77598759/creation-of-server-socket-failed-port-port-no-cannot-be-opened). I cannot find any references to `parallel` in the original package so perhaps it is tied in the `mirai::daemons()` call?

**Comment by shikokuchuo** [comment]
The simple answer is 'no'. `mirai` does not use any 'server socket' that would be referred to in the error message.

A search of GitHub shows that `serverSocket(port = port)` appears in the code for the `parallel` package in base R and the `parallelly` package (which is also used by `future`).

Whilst `mirai` can create parallel clusters, this is only done via it's `mirai::make_cluster()` function, which does not call into any of that codebase. If that package calls `parallel::makeCluster()` then that's an issue outside of `mirai`.
