### ISSUE TITLE
Impact on "select" function after running an eval_mirai 

### ISSUE THREAD

**Issue by ekianjo** [shikokuchuo/mirai#16]
Hi @shikokuchuo 
As part of my shiny application, I am currently experimenting with eval_mirai and things are working more or less as expected. A very strange behavior, however, is that when the eval_mirai has started, it suddenly breaks all my select() statements (from dplyr) inside my shiny app. The error I get is the following when a select is executed on a dataframe:

Warning: Error in select: Can't convert `NA` <unresolvedValue> to < integer >.

I can run these statements without issue before starting the eval_mirai, but once it's triggered, those break. I was thinking it could be some kind of variable conflict, but I double-checked and there is no variable name conflicting between the mirai process and the other tasks. I am also puzzled by the fact that it finds unresolvedValues for NAs in my dataframes where there should be none. 

Any clue on this?

**Comment by shikokuchuo** [comment]
This is the same as issue #8 - you need 'nanonext' >= 0.5.1 that's all, it was fixed in that release.
