### ISSUE TITLE
Decrement the assigned counter on stop_mirai()?

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#163]
I noticed `stop_mirai()` does not modify the `assigned` counter returned by `status()`. I think it would make sense to decrement it by 1 for the appropriate daemon. Decrementing `assigned` would allow me to more easily test my solution to https://github.com/wlandau/crew/issues/189.

``` r
library(mirai)
daemons(n = 1L)
#> [1] 1
task <- mirai(Sys.sleep(1e3))
status()
#> $connections
#> [1] 1
#> 
#> $daemons
#>                                     i online instance assigned complete
#> ipc:///tmp/362bb029eebe468d7500be60 1      1        1        1        0
Sys.sleep(2)
stop_mirai(task)
status()
#> $connections
#> [1] 1
#> 
#> $daemons
#>                                     i online instance assigned complete
#> ipc:///tmp/362bb029eebe468d7500be60 1      1        1        1        0
daemons(n = 0L)
#> [1] 0
```

<sup>Created on 2024-11-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.0 (2024-04-24)
#>  os       macOS 15.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Indiana/Indianapolis
#>  date     2024-11-04
#>  pandoc   3.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  cli           3.6.3      2024-06-21 [1] CRAN (R 4.4.0)
#>  digest        0.6.37     2024-08-19 [1] CRAN (R 4.4.1)
#>  evaluate      1.0.1      2024-10-10 [1] CRAN (R 4.4.1)
#>  fastmap       1.2.0      2024-05-15 [1] CRAN (R 4.4.0)
#>  fs            1.6.4      2024-04-25 [1] CRAN (R 4.4.0)
#>  glue          1.8.0      2024-09-30 [1] CRAN (R 4.4.0)
#>  htmltools     0.5.8.1    2024-04-04 [1] CRAN (R 4.4.0)
#>  knitr         1.48       2024-07-07 [1] CRAN (R 4.4.0)
#>  lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.4.0)
#>  mirai       * 1.3.0.9000 2024-11-04 [1] Github (shikokuchuo/mirai@4c87a44)
#>  nanonext      1.3.0.9003 2024-11-04 [1] Github (shikokuchuo/nanonext@84d61ac)
#>  reprex        2.1.1      2024-07-06 [1] CRAN (R 4.4.0)
#>  rlang         1.1.4      2024-06-04 [1] CRAN (R 4.4.0)
#>  rmarkdown     2.28       2024-08-17 [1] CRAN (R 4.4.0)
#>  rstudioapi    0.16.0     2024-03-24 [1] CRAN (R 4.4.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.4.0)
#>  withr         3.0.1      2024-07-31 [1] CRAN (R 4.4.0)
#>  xfun          0.48       2024-10-03 [1] CRAN (R 4.4.1)
#>  yaml          2.3.10     2024-07-26 [1] CRAN (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by shikokuchuo** [comment]
This request depends on the solution to #112 being implemented. `stop_mirai()` doesn't do anything beyond the user session at the moment.

Just as an aside though - perhaps we can start thinking if there's a way around these counters so you can start using threaded dispatcher. I'm open to ideas if you want to post another issue or discussion.

**Comment by wlandau** [comment]
A related question: I have come to really appreciate how `mirai` reassigns a failed task to the same listener on retry, and I do need to rely on it for https://github.com/wlandau/crew.cluster/issues/48. Will this carry over to the threaded dispatcher?

**Comment by shikokuchuo** [comment]
Good point. It should be an option but I don't think it is at the moment. Do you mind opening a new issue so I can track it?

**Comment by shikokuchuo** [comment]
> A related question: I have come to really appreciate how `mirai` reassigns a failed task to the same listener on retry, and I do need to rely on it for [wlandau/crew.cluster#48](https://github.com/wlandau/crew.cluster/issues/48). Will this carry over to the threaded dispatcher?

This will be addressed through https://github.com/shikokuchuo/mirai/pull/169, so we're just left with the original request here.
