### ISSUE TITLE
[Feature Request] return mirai objects from `everywhere()`

### ISSUE THREAD

**Issue by dgkf** [shikokuchuo/mirai#164]
I've finally landed on a good project for experimenting with `mirai` and I've been super impressed. 

All was going well until I started getting errors in some code I was calling with `everywhere()`. Not any issue with `mirai` directly - it turns out a web request I needed to make from each node was starting to error due to some server downtime. To debug the issues in `everywhere()`, I had to re-write it as single `mirai()` call to inspect the result.

It would be helpful if `everywhere()` returned a list of `mirai` objects similar to `mirai_map`. This would allow me to build some checks into my scripts for situations where successful execution relies on external factors.

```r
daemons(2)
ms <- everywhere({ 
  do_flaky_web_request()
  "success"
})

ms[]
ms[[1]]$data
#> [1] "success"

ms[[2]]$data
#> 'miraiError' chr Error in do_flaky_web_request: server timeout
```

**Comment by dgkf** [comment]
For the time being, I did something really hacky to return the vector of `mirai` connections already stored in `everywhere()`:

https://github.com/shikokuchuo/mirai/blob/92afc179be94781973e1a709cf24b0694c1018b6/R/mirai.R#L268
```diff
-   invisible()
+   invisible(vec)
```

```r
# modify `everywhere()` to return `vec`
everywhere <- mirai::everywhere
body(everywhere) <- bquote({ .(body(everywhere)); invisible(vec) })

ms <- mirai::collect_mirai(everywhere({
  do_flaky_web_request()
  "success"
}))

if (any(is_error <- vapply(ms, mirai::is_mirai_error, logical(1L)))) {
  stop("issues encountered during daemon setup")
}
```

This let me terminate early when anything goes wrong. In practice, I can also expose things like individual node error messages and stack traces stored in the `mirai` error objects.

Although modifying a function body is a last resort, I was impressed by how simple the change was.

**Comment by shikokuchuo** [comment]
Thanks Doug. I'm persuaded of the benefits of your request.

Leave this with me - it may take some time as I might be updating the underlying implementation (currently comprised of mirai calls) - and I don't want to be changing the API too often.

**Comment by shikokuchuo** [comment]
This has been incorporated now in mirai 1.3.1.9022 (what will be mirai v2). `everywhere()` now returns a list of mirai.
