### ISSUE TITLE
mirai_map daemons fail after 13 jobs when creating data.tables

### ISSUE THREAD

**Issue by D3SL** [shikokuchuo/mirai#166]
I've started looking into switching to mirai from `furrr` and ran into a _strange_ issue with `mirai_map()`. When creating a data.table inside `mirai_map()` there seems to be a hard limit of 13-14 jobs per daemon after which they fail with `'errorValue' int 19 | Connection reset`. I'm making a complete blind guess but I would not be surprised if this is due to data.table's reference semantics and use of a pointer inside each data.table.

The snippet below will let you test this easily just by changing the value of `mult`. 1 daemon will complete 13 rows before failing. 2 will complete 26, 3 complete 39, and so on. If `data.table()` is changed to `tibble()` or `data.frame()` there's no issue.

```R
library(mirai)
library(data.table)

mult<-1
daemons(mult)

mirai_out<-mirai_map(
  data.table(row_id=1:(13*mult+5)),
  function(row_id){
    library(data.table)
      foo<-data.table(foo=row_id)
  }
)
# On reaching row 13 each daemon hangs and eventually disconnects
mirai::status()
```

**Comment by D3SL** [comment]
Interesting. When I took the original example and replaced `data.table(foo=row_id)` with `data.frame(foo=row_id)` while still calling `library(data.table)` it worked fine, which made me think it wasn't the library call.

**Comment by shikokuchuo** [comment]
It is indeed more interesting than it first appears. It's not the library call _per se_ - by default mirai cleans up after each evaluation to ensure that each is self-contained. At the moment it detaches and unloads the shared library of packages that were added. Now this is not always safe to do.

Quoting the help for `?dyn.unload`:

> The function dyn.unload unlinks the DLL. Note that unloading a DLL and then re-loading a DLL of the same name may or may not work: on Solaris it used the first version loaded. Note also that some DLLs cannot be safely unloaded at all: unloading a DLL which implements C finalizers but does not unregister them on unload causes R to crash.

Your original example, specifying `cleanup = FALSE` at `daemons()` also works:
```r
library(mirai)
library(data.table)

mult<-1
daemons(mult, cleanup = FALSE)

mirai_out<-mirai_map(
  data.table(row_id=1:(13*mult+5)),
  function(row_id){
    library(data.table)
      foo<-data.table(foo=row_id)
  }
)
```
What I think I will do is disable attempting to unload the shared libraries in the detach call. I don't believe this would affect any subsequent R evaluation. Copying @wlandau in case you have contrary experience.

**Comment by D3SL** [comment]
Based on your quote about C finalizers do you think this is something that can also be addressed at the data.table side?

**Comment by shikokuchuo** [comment]
> Based on your quote about C finalizers do you think this is something that can also be addressed at the data.table side?

The quote was to highlight the general problem. It's probably not C finalizers. I don't propose that it's specific to `data.table` or that they need to fix this. The linked PR will make sure you don't encounter this in any case.

**Comment by shikokuchuo** [comment]
@D3SL if you did want to raise it at `data.table`, I did find a simple reprex only involving `data.table` that reproduces a crash here: https://github.com/shikokuchuo/mirai/pull/167#issuecomment-2469004000. In any case, I'm going to merge that PR so it's no longer an issue for `mirai`. Thanks for reporting.
