### ISSUE TITLE
Automatic down-scaling in server()

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#19]
For my distributed computing use case, automatic down-scaling would be extremely helpful in order to avoid excessive idle time and to proactively avoid hitting walltime limits on clusters. It would be extremely useful if `server()` could automatically terminate if

1. If it has been idling for too long without receiving a task (idle timeout), or
2. If the total runtime of the server reaches a limit and that server has no currently assigned jobs (soft walltime), or
3. If it has already completed a given number of tasks (task limit).

It would be great to have new arguments to `server()` to set the max idle time, soft walltime limit, and max number of tasks.

**Comment by wlandau** [comment]
I forgot to mention soft walltime. Added to the original post.

**Comment by shikokuchuo** [comment]
These have been implemented in ae8884b. Note that this will need to evolve to be in step with the other features as they are added.

**Comment by wlandau** [comment]
Really glad to see this! I will test on my end as soon as I have a free moment.

**Comment by wlandau** [comment]
I tested `idletime` and `tasks`, and they work beautifully! `runtime` works a little differently than I thought it would (seems to start the clock when the first task begins, then make a stop/continue decision at the conclusion of each task), but I still like it. Thanks!
