### ISSUE TITLE
Informative error messages

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#21]
If I call `daemons(0)` while servers on the connection are running, `server()` correctly exits, but the error message is strange:

```r
attempt to bind a variable to R_UnboundValue
```

Other times I get:

```r
Error in server("tcp://xx.xx.xx.138:5555") : object 'envir' not found
```

It's a minor thing, but more descriptive error messages would help me troubleshoot complicated user errors on my end.

**Comment by shikokuchuo** [comment]
The former is one of the package's best features!

The second one is is a bit perplexing... as execution should never reach that point in the code. May be a bug in R's error handling, but I don't know it well enough to say definitively.

In any case, I have made server instances completely silent now and they exit cleanly. v0.7.2.9006.

**Comment by wlandau** [comment]
> The former is one of the package's best features!

I completely agree! I love that the servers quit on `daemons(0)`. 

> The second one is is a bit perplexing... as execution should never reach that point in the code. May be a bug in R's error handling, but I don't know it well enough to say definitively.

If I see it again, I will post a reprex.

> In any case, I have made server instances completely silent now and they exit cleanly. v0.7.2.9006.

Tested on my end, and it works beautifully.

**Comment by shikokuchuo** [comment]
> If I see it again, I will post a reprex.
> 
No need for the reprex - I see it my end as well! Truly mysterious, but not serious enough to bother me...
