### ISSUE TITLE
Trouble after update with custom TCP sockets

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#27]
Version 0.7.2.9010 with custom TCP sockets looks promising. However, I am having a bit of trouble with the active queue after the update up to https://github.com/shikokuchuo/mirai/commit/e9a6edddbd8b0ac7cdc587e1827b7faf2c9049ca. On the client, I tried:

```r
library(mirai)
daemons("tcp://127.0.0.1:5000", nodes = 1)
```

And with a server process on the same machine as the client:

```r
library(mirai)
server("tcp://127.0.0.1:5000")
```

Then back on the client, I see:

```r
daemons()
#> $connections
#> [1] 0
#> 
#> $daemons
#> [1] "remote"
#> 
#> $nodes
#> [1] 1
```

And a quick `mirai()` looks unresolved after about 10 seconds.

```r
m <- mirai::mirai(ps::ps_pid())
Sys.sleep(10)
m$data
#> 'unresolved' logi NA
```

**Comment by shikokuchuo** [comment]
I just tried that commit installing from r-universe. Your code above runs fine. Perhaps there is a dead proccess on that port?

**Comment by wlandau** [comment]
I just tried ports 50001, 50002, and 57000, all with the same result. I was running the R-universe builds of `mirai` 0.7.2.9010 and `nanonext` 0.7.3.9004.

**Comment by shikokuchuo** [comment]
Are you on Windows perchance?

**Comment by wlandau** [comment]
I was trying it on a login node of my company's SGE cluster, which runs RHEL 7. It works on my local Macbook though.

**Comment by shikokuchuo** [comment]
I wonder if it is something to do with shell scripting. Does your RHEL 7 run some other shell? what if you run bash explicitly before launching the R sessions. I will investigate my side as well

**Comment by wlandau** [comment]
I am running zsh in for both. It's not easy to switch my default shell, but I tried launching bash in both terminals before calling R, and that did not fix the problem on my end.

**Comment by shikokuchuo** [comment]
I have just pushed 0.7.2.9011. Please have a try with this one. Thanks!

**Comment by wlandau** [comment]
I just tried again with https://github.com/shikokuchuo/mirai/commit/6926b19ed9ba79e581b64370149b1ed441702f1e, and the result is the same.

**Comment by shikokuchuo** [comment]
I have just realised you are using the 127.0.0.1 loopback address! That is more trouble than it's worth. I assume that currently nothing works on that address on your enterprise setup not just `daemons("tcp://127.0.0.1:5000", nodes = 1)` but also `daemons("tcp://127.0.0.1:5000")`?

**Comment by wlandau** [comment]
I just retried with `nodes = 1` with the address from `getip::getip(type = "local")`, and it still did not work. The loopback address does work if I do not set the `nodes` argument.

**Comment by shikokuchuo** [comment]
Can you please help me report what works out of:

daemons(1)
daemons(1, nodes = 2)
daemons("tcp://:5555")
daemons("tcp://:5555"), nodes = 1)
daemons("tcp://:5555"), nodes = 2)

If needs be, we'll start again from the working build.

**Comment by wlandau** [comment]
Looks like there is trouble with `daemons(1)`. On SGE:

```r
> library(mirai)
> daemons(1)
[1] 1
> Sys.sleep(10)

> daemons()
$connections
[1] 0

$daemons
[1] 1

$nodes
[1] NA

> m <- mirai("output")
> Sys.sleep(10)
> m$data
'unresolved' logi NA
```

On my local Macbook:

```r
> library(mirai)
daemons(1)
Sys.sleep(10)
daemons()
m <- mirai("output")
Sys.sleep(10)
m$data
> daemons(1)
[1] 1
> Sys.sleep(10)
> daemons()
$connections
[1] 1

$daemons
[1] 1

$nodes
[1] NA

> m <- mirai("output")
> Sys.sleep(10)
> m$data
[1] "output"
```

**Comment by wlandau** [comment]
Is that enough information?

**Comment by wlandau** [comment]
With `nodes = 2` on SGE:

```r
> library(mirai)
> daemons(1, nodes = 2)
[1] 1
> Sys.sleep(10)

> daemons()
$connections
[1] 0

$daemons
[1] 1

$nodes
[1] 2

> m <- mirai("output")
> Sys.sleep(10)
> m$data
'unresolved' logi NA
```

**Comment by shikokuchuo** [comment]
Yes, thanks. So on both of the above, and why your custom URL nodes doesn't work is the local background process on the SGE machine is not launching.

**Comment by shikokuchuo** [comment]
Do you still have access to v0.7.2.9009 the build we think is working? Did you try the same with that build?

**Comment by shikokuchuo** [comment]
I can roll back if you think it helps, but I don't think any change since then would have broken the above.

Is it possible for you to replicate the working tests that you had reported before using the current build. Alternatively run what is failing now on a previous build.

At least we will know if we should start from an earlier point or the current point. Thanks!

**Comment by shikokuchuo** [comment]
Also can you let me know the value of
`mirai:::.command` and 
`mirai:::.urlfmt`
on both your SGE machine and Macbook
Thanks!!

**Comment by wlandau** [comment]
I just tried 7f421e376512d9a3e323e4a561e0461112ef5948 but unfortunately ran into the same problem with `daemons(1)`. Not sure how far back I would have to go.

`mirai:::.command` yields a valid Rscript path on both machines.

`mirai:::.urlfmt` yields "ipc:///tmp/n%.f" on my Macbook and "abstract://n%.f" on RHEL7/SGE.

**Comment by wlandau** [comment]
Yes, `file.path(R.home("bin"), "Rscript") == mirai:::.command` returns `TRUE`. The path is `R-4.2.2/lib64/R/bin/Rscript` relative to the directory where the R installations live.

**Comment by shikokuchuo** [comment]
Right... so that is ruled out.

Please can you try this in your client process:
```r
daemons("abstract://test")
```

In another shell:
```
Rscript --vanilla -e 'mirai::server(c("abstract://test","tcp://127.0.0.1:5556"),nodes=1)'
```
In another shell:
```
Rscript --vanilla -e 'mirai::server("tcp://127.0.0.1:5556")'
```
Can you receive a mirai in the main process? Does `daemons(0)` exit both processes?

Try this also:

```r
daemons("tcp://127.0.0.1:5555")
```

In another shell:
```
Rscript --vanilla -e 'mirai::server(c("tcp://127.0.0.1:5555","tcp://127.0.0.1:5556"),nodes=1)'
```
In another shell:
```
Rscript --vanilla -e 'mirai::server("tcp://127.0.0.1:5556")'
```

Thanks again for testing this. The result of the above will let us know whether it is an issue with executing the command or the Linux abstract domain sockets in RHEL7.

**Comment by wlandau** [comment]
I think I found the answer! `Rscript --vanilla -e 'mirai::server(...)'` returns:

```
Error in loadNamespace(x) : there is no package called ‘mirai’
```

because I am using a personal package library on the SGE cluster (I cannot install `mirai` to system-level R because our devops team does that). In `mirai`, I see:

https://github.com/shikokuchuo/mirai/blob/6926b19ed9ba79e581b64370149b1ed441702f1e/R/mirai.R#L765-L767

I bet that explains it.

**Comment by shikokuchuo** [comment]
OK! let me find the right arguments then -  `--vanilla` seems like just won't cut it.

**Comment by shikokuchuo** [comment]
Seems just removing it is the best option. It should then pick up your site/user profiles or environment files. I did some quick tests, doesn't really impact performance. I had used for extra safety but I think that caution was probably unwarranted.

v0.7.2.9012 (3f2d2d5). Enjoy!

**Comment by shikokuchuo** [comment]
You're welcome. I am so glad we fixed this!!
