### ISSUE TITLE
server() and SIGINT

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#29]
In testing, I often run `server()` interactively and then try to stop it with CTRL-c, but it does not seem to respond to SIGINT. How easy would it be to allow interrupts? This is not essential to my use case, simply nice to have if it's easy. If it's hard, please don't worry about it.

**Comment by shikokuchuo** [comment]
NNG when blocking is uninterruptible. By design. Search SIGINT on NNG github issues :)
Partly why I implemented the `daemons(0)` kill switch.

Easy solution is CTRL + \ to kill the R process.

**Comment by shikokuchuo** [comment]
For testing the server, I tend to launch in the shell via Rscript. Easier and faster than going into an R prompt.

**Comment by wlandau** [comment]
CTRL + \ works great, thanks!
