### ISSUE TITLE
Active queue daemons continue to run unless servers are connected first

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#32]
On the client on my local Macbook, I watched `htop` as I ran the following.

```r
library(mirai)
daemons("tcp://127.0.0.1:45000", nodes = 1, .compute = "p1")
#> [1] "remote"
daemons("tcp://127.0.0.1:45500", nodes = 2, .compute = "p2")
#> [1] "remote"
daemons(0, .compute = "p1")
#> [1] 0
daemons(0, .compute = "p2")
#> [1] 0
```

Each time called I `daemons()` with a socket, I noticed a new R process (for the active queue daemon, right?). If I don't connect any servers and instead call `daemons(0)` on the compute profile, those active queue processes kept running.

It was also interesting and helpful to see that each compute profile created its own daemon to run its own active queue. I don't anticipate having very many compute profiles, so I can work with that.

**Comment by shikokuchuo** [comment]
The above actually runs fine and exits cleanly for me. I think my fix for #30 also addresses this.

**Comment by wlandau** [comment]
Indeed, looks fixed to me. Thanks!

**Comment by shikokuchuo** [comment]
Turns out it's not so simple, need an initialisation time as you suggest, which works for me as 200ms. I thought about adding a guard when creating a new connection - but then decided against as it is really only in testing where you are going to see this.

```r
for (i in 1:100) {daemons(n = 5L, url = "ws://127.0.0.1:5000"); Sys.sleep(0.2); daemons(0)}
```
For me the above runs fine without leaving any open tasks.

**Comment by wlandau** [comment]
Thanks for confirming. In https://github.com/wlandau/crew/commit/36c6af8682753d31891e5fa5895460dc1603f79d, just to be extra safe I enforced a 1s lifespan for the dispatcher and client.

**Comment by shikokuchuo** [comment]
That's helpful for framing it as minimum lifespan!

I had been doing an msleep at socket creation but that led to a noticeable pause even at 0.2s. Now I just check and enforce when attempting to close the socket. This is implemented in the CRAN release.

The following now runs without problem:
```r
for (i in 1:100) {daemons(n = 5L, url = "ws://127.0.0.1:5000"); daemons(0)}
````
You may remove the workaround on your side.

When I finish implementing shikokuchuo/nanonext@405c7e4 then it will actually be possible to ***synchronise*** between client and dispatcher!

**Comment by wlandau** [comment]
> The following now runs without problem

Awesome! Confirmed on my end too.

> When I finish implementing https://github.com/shikokuchuo/nanonext/commit/405c7e4 then it will actually be possible to synchronise between client and dispatcher!

Will this allow the dispatcher confirm to the client exactly when is ready to receive interrupt signals, or otherwise exit if this handshake fails? Seems like this would definitely help prevent the dispatcher from persisting in the background indefinitely after the client exits.
