### ISSUE TITLE
Edge case when mirai is submitted with no server connected

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#33]
When I submit a `mirai` without disconnecting a server first, I run into errors polling the nodes. Then if I restart my R session, I see a segfault and the active queue daemon keeps running in the background. Things start working again as soon as I manually terminate the local active daemon process.

On my end, I will implement safeguards in `crew` to only launch a `mirai`s when there is at least one server connected (the server could be busy though). Is there a way for `mirai` to make sure active queue daemons are cleaned up in cases like this one?

```r
> library(mirai)
> daemons("tcp://127.0.0.1:5000", nodes = 1)
[1] 1
> daemons()
$connections
[1] 1

$daemons
[1] 1

$nodes
tcp://127.0.0.1:5000 
                   0 

> m <- mirai(1)

> daemons()
$connections
[1] 1

$daemons
[1] 1

$nodes
'errorValue' int 5 | Timed out
```

**Comment by wlandau** [comment]
I do also notice "'errorValue' int 5 | Timed out" when tasks are running. Could be related.

```r
# client
library(mirai)
daemons("tcp://127.0.0.1:5000", nodes = 1)

# server
mirai::server("tcp://127.0.0.1:5000")

# client again
Sys.sleep(0.5)
daemons()
#> $connections
#> [1] 1
#> 
#> $daemons
#> [1] 1
#> 
#> $nodes
#> 'errorValue' int 5 | Timed out
```

**Comment by wlandau** [comment]
But the `mirai()` from https://github.com/shikokuchuo/mirai/issues/33#issue-1607328627 succeeds as soon as I run a server. So I think my main observations at this point are just

1. `'errorValue' int 5 | Timed out` when I expected to see the TCP sockets in `$nodes`, and
2. An active queue daemon that sometimes keeps running if the parent R session terminates at a bad time.

**Comment by shikokuchuo** [comment]
This is an architectural issue for the active queue. The current implementation has one channel of communication. 

So the issue you've found is that commands (status query, exit) can get queued behind tasks. This isn't going to be very common in realistic situations where there are several nodes - but just having one node and no actual connection then sending a mirai blocks everything after it including the exit signal. Note that in this case if you had set `nodes = 2`, even without any connections, both the status and exit would work fine.

A clean solution would necessitate a second (IPC) channel into the queue. A bit like a sever admin management channel. I am not convinced that is necessary.

**Comment by shikokuchuo** [comment]
Currently the status query is synchronous, hence the potential for the 1s wait and timeout. An alternative would be to just return an Aio. It would remain 'unresolved' until it can be processed by the queue.

**Comment by wlandau** [comment]
Thanks for explaining, that's very helpful.

Have you considered launching the active queue daemon with `callr::r_bg(supervise = TRUE)` instead of `system2()`? It prevents child processes from running after the parent process exits. I'm not sure it would work in this case if operating system signals sometimes get blocked just like everything else.

**Comment by shikokuchuo** [comment]
There are currently multiple safeguards that all send the exit signal when the parent exits, and this cascades down.

I find that even in a case with one node that is busy, once the computation finishes then they do exit by themselves. Let me know if you find a case where this doesn't happen.

**Comment by wlandau** [comment]
Thanks, I will let you know.

**Comment by shikokuchuo** [comment]
Another alternative would be to add an option for logging the status periodically to file. This also gets around having a second connection.

In any case, if you find this does become a problem in real usage then feel free to re-open. It is something that is easily solvable.

**Comment by shikokuchuo** [comment]
I have resolved this in [9ce8bfd](https://github.com/shikokuchuo/mirai/commit/9ce8bfd4e94ee12c2da21b6e64868c1e62e1d0f7) by adding the second channel into the active queue. It should now be possible to query the status at any time. This actually makes the queue logic a little bit cleaner as well.

**Comment by wlandau** [comment]
Wow! Thank you so much! And I am glad the implementation process made things simpler rather than more complicated on your end.

Between this and https://github.com/shikokuchuo/mirai/discussions/31#discussioncomment-5204501, it sounds like `mirai` will be completely perfect for `crew`. If all goes well in the development and testing I plan to do this upcoming week, I will be able to use `mirai` and only `mirai` as `crew`'s task scheduler!

**Comment by wlandau** [comment]
By the way, does this second channel need another port? If so, NNG safely chooses one automatically, right? (2 ports total per active queue daemon is totally workable for me.)

**Comment by shikokuchuo** [comment]
No it is purely an IPC connection - abstract unix domain socket on Linux, named pipes on Windows etc. Very light.

**Comment by wlandau** [comment]
Tested on my end and I can always get the status of the websockets with `daemons()$nodes`! Magic!
