### ISSUE TITLE
A min tasks argument to server()? 

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#34]

**Comment by wlandau** [comment]
I am working through how `crew` launches workers, and I find myself in need of a step right after launch that checks that a worker successfully connected. If the worker idles out before I can check it, that creates a problem. It would be great to have the option to suspend the clock on idle time until the worker receives a task.

**Comment by wlandau** [comment]
On second thought, I am not sure I need this to finish implementing `crew`, but it might be nice for users anyway.

**Comment by shikokuchuo** [comment]
Yes you're right - now in [f7d7d2f](https://github.com/shikokuchuo/mirai/commit/f7d7d2f456036390cffc800b28887b56deb2519c) the idle timer starts when the first node connects rather than when the queue launches. It no tasks are sent it will still idle out, but shouldn't that be the case? if a task is sent, the idle timer only restarts after the task is finished.

**Comment by shikokuchuo** [comment]
Oh I see what you mean - for each individual node? You want to start the idle timer only after the first task and have it waiting indefinitely for the first one?

**Comment by wlandau** [comment]
I think I may have posted too soon, sorry to bother you. I need to go back and think harder about the auto-logic in `crew`.

**Comment by wlandau** [comment]
Yes, thank you, I like https://github.com/shikokuchuo/mirai/commit/f7d7d2f456036390cffc800b28887b56deb2519c. If `crew`'s auto-scaling works (I may not be able to test again for another few days) then do not foresee a situation where it is would be good to idle out a worker before any work actually began. And this new behavior makes `idletime` consistent with `walltime`, the latter of which waits to receive a task before starting the clock.

**Comment by shikokuchuo** [comment]
In commit [51f2f80](https://github.com/shikokuchuo/mirai/commit/51f2f80c360d872437fd9a17def3ae20184edf79) I add the `timerstart` argument to `server()` which addresses this issue, and allows timers to start after one or an arbitrary number of tasks has been completed.

By default this is zero, as logically servers should obey the `idletime` directive, but I can see this may be useful if it is costly and takes a long time to start remote resources and hence should be kept alive initially.

Note that `tasklimit` is now `maxtasks` (I like to optimise argument names for partial matching as much as possible - single letter matching is in force for `nanonext` at least).

I have removed these limits at the active queue level for now, as I need to think what makes sense here. I think mostly you'd want the queue to persist regardless of settings for individual nodes. But I also need to consider the case where an active queue is launched remotely as opposed to local queue / remote nodes.

**Comment by wlandau** [comment]
> In commit [51f2f80](https://github.com/shikokuchuo/mirai/commit/51f2f80c360d872437fd9a17def3ae20184edf79) I add the timerstart argument to server() which addresses this issue, and allows timers to start after one or an arbitrary number of tasks has been completed.

Thanks, I really like this. I tested `timerstart` in combination with `idletime`, and it works as expected. However, `walltime` seems to behave as if `timerstart` is really `timerstart + 1L`. If I call `mirai::server("ws://127.0.0.1:5000/1", walltime = 1000, timerstart = 0L)`, the server seems to wait until the first task starts before starting the timer.

**Comment by wlandau** [comment]
> I have removed these limits at the active queue level for now, as I need to think what makes sense here. I think mostly you'd want the queue to persist regardless of settings for individual nodes. But I also need to consider the case where an active queue is launched remotely as opposed to local queue / remote nodes.

For my use case with the local active queue on the client machine, I indeed want the active queue daemon to start at `daemons("ws://...", nodes = ..., .compute = "my_profile")` and keep running until `daemons(0, .compute = "my_profile")`. For `crew`, I do not plan to use the remotely-launched server-specific active queues.

**Comment by shikokuchuo** [comment]
> > In commit [51f2f80](https://github.com/shikokuchuo/mirai/commit/51f2f80c360d872437fd9a17def3ae20184edf79) I add the timerstart argument to server() which addresses this issue, and allows timers to start after one or an arbitrary number of tasks has been completed.
> 
> Thanks, I really like this. I tested `timerstart` in combination with `idletime`, and it works as expected. However, `walltime` seems to behave as if `timerstart` is really `timerstart + 1L`. If I call `mirai::server("ws://127.0.0.1:5000/1", walltime = 1000, timerstart = 0L)`, the server seems to wait until the first task starts before starting the timer.

I think this is an artefact of how you were testing it. `walltime` was always a soft walltime concept, so it would wait for anything in progress. Of course this doesn't make sense if it's just waiting for a task so I've fixed this in [d7bf569](https://github.com/shikokuchuo/mirai/commit/d7bf569ced0bdedf01b991fc7c26cbb0ad9c6a43).

**Comment by shikokuchuo** [comment]
> > I have removed these limits at the active queue level for now, as I need to think what makes sense here. I think mostly you'd want the queue to persist regardless of settings for individual nodes. But I also need to consider the case where an active queue is launched remotely as opposed to local queue / remote nodes.
> 
> For my use case with the local active queue on the client machine, I indeed want the active queue daemon to start at `daemons("ws://...", nodes = ..., .compute = "my_profile")` and keep running until `daemons(0, .compute = "my_profile")`. For `crew`, I do not plan to use the remotely-launched server-specific active queues.

Thanks for letting me know. I have something that should make sense for most use cases (including yours) in v0.7.2.9030.

**Comment by shikokuchuo** [comment]
A final `exitdelay` parameter should round up the required changes on this front. Looks good from my perspective. v0.7.2.9032.

**Comment by wlandau** [comment]
I wonder if an exit delay is the best way to handle sends of large data. What about a checksum to detect an incomplete send, or delaying the timeout until the current send is complete?
