### ISSUE TITLE
CRAN 0.8.0 release changes

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/mirai#36]
Just giving notice that I am looking at the interface and parameter names prior to launch of the next CRAN release. It is just the UI that I want to optimise - all existing functionality will be preserved.

So far, may just be limited to `daemons()` - perhaps going back to the
```r
daemons(n, url, q = TRUE)
```
type of interface. There is no real need to pass through arguments for either local or remote daemons and I don't think this is intuitive at the moment.

@wlandau I guess a CRAN release will also help you make `crew` available to a wider audience for testing.

**Comment by wlandau** [comment]
Yes it will! `crew` has not yet caught up to all the great work you have done in `mirai`, so I may have more feature requests after this latest CRAN release. But yes, I think a release would definitely help.

As far as changes to the interface, would you let me know if other breaking changes happen? currently I am using the full `nodes` argument instead of `n` for `daemons()`. To start a local active server queue:

```r
daemons(value = "ws://198.162.0.2:5000", nodes = 4, .compute = "worker_group_id")
```

And then to check the status of the nodes:

```{r}
mirai::daemons(.compute = "worker_group_id")
```

So does that mean the `nodes` argument will change to `n` and the `value` argument will change to `url`? Would you please keep the `.compute` argument as discussed in #23? And would you let me know about other potentially breaking changes?

**Comment by shikokuchuo** [comment]
I will of course let you look over before actually submitting! But yes, may just be 'n' and 'url' in `daemons()`. I don't see much need to change `server()` at the moment.

That's fine with further changes - with my release frequency can definitely put out another one before `crew` hits prime time.

**Comment by shikokuchuo** [comment]
oh yes `.compute` won't change. I meant those may be the only arguments that actually change.

**Comment by shikokuchuo** [comment]
I will need to update the docs and readme, so no need to look at it yet, but the broad outline is as per the below.

```r
daemons(n, url = NULL, active = TRUE, ..., .compute = "default")
```
`daemons()` will now return `$connections` and `$daemons` - which is a scalar for active = FALSE and the matrix if active = TRUE.

Essentially I am abstracting away from the concept of the active queue and daemons/nodes. Daemons are the processes you want, and `active` toggles the dispatch behaviour (I am moving away from the queue terminology).

**Comment by shikokuchuo** [comment]
Todo: split out `server()` into `server()` and `dispatcher()`, as there are already 2 code paths. Will allow `dispatcher()` to be used on a modular basis.

**Comment by wlandau** [comment]
Will I still use server() for crew workers (local active server queue to load balance over different server websockets), or should I switch to calling dispatcher()?

**Comment by shikokuchuo** [comment]
> Will I still use server() for crew workers (local active server queue to load balance over different server websockets), or should I switch to calling dispatcher()?

You would still call server() on your remote instances, and daemons() would call dispatcher() behind the scenes on the client.

The real advantage is that if you take dispatcher(), you could take tasks from many sources and dispatch to many servers, something that isn't possible at the moment.

I hope to bed down the changes over this weekend and fully document.

Aim is to lay down the UI so it doesn't change going forward. If there are breaking changes, I would rather make big ones once than constantly changing the interface!

Just to give you a heads-up I have exciting plans for nanonext at the C level that will for example completely eliminate the need for polling at the dispatcher.

**Comment by shikokuchuo** [comment]
This is now complete as of v0.7.2.9040. Appreciate any testing to ensure nothing got lost in translation. Submit to CRAN next week barring any major issues.

Apart from bugs, suggestions also welcome as to naming etc. if anything doesn't seem quite right or feel quite natural.

Main change is active dispatch is now default for daemons (it has evolved so much!), and the distinction between daemons and nodes is gone, with the dispatcher now a transparent part of the picture.

The daemons interface now takes a numeric 'n' and character 'url' argument. 'n' does not need to be specified if this can be implied from the length of the 'url' vector.

`server()` is almost the same as before - with argument name 'exitdelay' changed to 'exitlinger' to more accurately describe what this is and bring it in line with sockets speak. The 'queue' specific arguments such as poll frequency is moved to `dispatcher()`.

`dispatcher()` can now be called separately. Currently still only connecting to one client for simplicity - I have not implemented multi-client yet. `daemons()` calls this behind the scenes so it should not be necessary to call this separately.

`daemons()` status format is simplified with just `$connections` and `$daemons`, with cosmetic changes in the matrix names.

If I have time, would like to improve the README a bit but it should at least be current.

**Comment by shikokuchuo** [comment]
and the obvious omission was the '...' pass-through for local processes directly launched by `daemons()` or `dispatcher()`.

Present in v0.7.2.9041

**Comment by wlandau** [comment]
Thanks for all the info. I believe the lower-level `crew` objects are now caught up with all the API changes in `mirai`. I still need to rewrite much of `crew` to catch up with the bigger developments, and I plan to do that this week. I foresee it going smoothly with the current version of `mirai`.

**Comment by shikokuchuo** [comment]
Fantastic!

I have made one last change which is substituting `dispatcher` for `active` for the argument name in `daemons()`. This is important as:
- argument name is obvious without needing to read the explanation of what it means
- clear that if `dispatcher = TRUE` you are adding the dispatcher 'module'
- no obvious connotations favouring one state vs the other, whereas 'active' probably deters users from choosing FALSE
- simplified documentation of what dispatcher is that applies across scenarios

I will now not make any further changes for the next couple of days so we can detect problems if there are any. Version is 0.7.2.9042.

Any new commits will only be to round out the documentation / readme.

**Comment by shikokuchuo** [comment]
Final changes that will make the cut:
- minimum 1s timespan for sockets (as detailed in other issue chain)
- length 1 URL (without specifying 'n') is treated as vectorised by dispatcher (won't modify it) - @wlandau please note - this was a regression during the recent changes
