### ISSUE TITLE
Trouble passing arguments to daemons() which are forwarded to dispatcher()

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#41]
I think it is because I am calling `daemons()` inside an `R6` class and some of these forwarded arguments are fields of the object. I am fine to hard-code `asyncdial = TRUE` in `crew`, but I suspect a more general problem about environment scoping.

Using the `asyncdial` field, `daemons()` errors out:

```r
class <- R6::R6Class(
  classname = "test",
  public = list(
    asyncdial = TRUE,
    listen_for_servers = function() {
      socket <- "ws://10.0.0.9:59604"
      mirai::daemons(
        url = socket,
        n = 1L,
        dispatcher = TRUE,
        asyncdial = self$asyncdial
      )
    },
    run_test = function() {
      self$listen_for_servers()
      Sys.sleep(2)
      px <- callr::r_bg(
        function(socket) mirai::server("ws://10.0.0.9:59604")
      )
      Sys.sleep(2)
      print(mirai::daemons())
      m <- mirai::mirai(ps::ps_pid())
      Sys.sleep(2)
      print(m$data)
      mirai::daemons(0L)
      invisible()
    }
  )
)
object <- class$new()
object$run_test()
#> Error in request_ack(sock) : 
#>   dispatcher process launch - timed out after 1s
```

Hard-coding `asyncdial`, everything works:

```r
class <- R6::R6Class(
  classname = "test",
  public = list(
    asyncdial = TRUE,
    listen_for_servers = function() {
      socket <- "ws://10.0.0.9:59604"
      mirai::daemons(
        url = socket,
        n = 1L,
        dispatcher = TRUE
      )
    },
    run_test = function() {
      self$listen_for_servers()
      Sys.sleep(2)
      px <- callr::r_bg(
        function(socket) mirai::server("ws://10.0.0.9:59604")
      )
      Sys.sleep(2)
      print(mirai::daemons())
      m <- mirai::mirai(ps::ps_pid())
      Sys.sleep(2)
      print(m$data)
      mirai::daemons(0L)
      invisible()
    }
  )
)
object <- class$new()
object$run_test()
#> $connections
#> [1] 1
#> 
#> $daemons
#> status_online status_busy tasks_assigned tasks_complete instance #
#> ws://10.0.0.9:59604             1           0              0              0          1
#> 
#> [1] 55721
```

**Comment by shikokuchuo** [comment]
Have some time between meetings and fixed the other issue. This is strange - I'm not an expert on R6 at all but seems like it should work! As this is the IPC connection between client and dispatcher it is safe to hard code this as TRUE from my perspective.

On the other hand I am getting only one test error at the moment crew_router. I wonder if this is related.

Error ('test-crew_router.R:57:3'): crew_router() works ──────────────────────
<crew_expire/crew_error/crew/rlang_error/error/condition>
Error: timed out after waiting 5 seconds. 
Backtrace:
    ▆
 1. └─crew::crew_wait(...) at test-crew_router.R:57:2
 2.   └─crew:::crew_expire(message)
 3.     └─crew:::crew_stop(...)
 4.       └─rlang::abort(message = message, class = class, call = emptyenv())

**Comment by shikokuchuo** [comment]
Yes, was using the CRAN version. Was thinking it'd be good not to break your package. But if you are planning to release beforehand and your changes are back compatible with nanonext 0.8.0 and mirai 0.8.1 then by all means ignore.

**Comment by shikokuchuo** [comment]
Hard coded in https://github.com/wlandau/crew/releases/tag/0.0.5

**Comment by shikokuchuo** [comment]
>  I suspect a more general problem about environment scoping.

It's not that. It suddenly occurred to me - it's down to my use of `substitute(alist(...))` to construct the language object to form the command line string. `alist()` does not evaluate the `...` - how subtle is that!!

**Comment by shikokuchuo** [comment]
`as.expression(list(...))` does the job!

**Comment by shikokuchuo** [comment]
@wlandau actually 'asyncdial' should be taken out as an argument for the R6 class. Yes it can be passed on through '...', but for both dispatcher and server the argument is designed for when launching those remotely to debug for connection errors (mostly firewalled ports). It doesn't make sense to specify as part of a daemons() call.

**Comment by wlandau** [comment]
That makes sense. Removed in https://github.com/wlandau/crew/commit/aae86416ddf2939842cb59894e536711e58dc5eb.
