### ISSUE TITLE
task does not complete if saisei() is called before launching the server

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#47]
As I work on https://github.com/wlandau/crew/issues/61, I notice that my tasks do not complete if the socket is switched with `saisei()` before the server connects. 

```r
library(mirai)
packageVersion("nanonext")
#> [1] ‘0.8.1.9006’
packageVersion("mirai")
#> [1] ‘0.8.2.9004’
packageDescription("mirai")$GithubSHA1
#> [1] "f74b480b1c7c33c700030ca1972aa9bee362cd8d"
daemons(n = 1L, url = "ws://127.0.0.1:5000", dispatcher = TRUE, token = TRUE)
#> [1] 1
task <- mirai(ps::ps_pid())
socket <- saisei(i = 1L)
px <- callr::r_bg(
  func = function() mirai::server(url = socket, asyncdial = FALSE),
  args = list(socket = socket)
)
Sys.sleep(10)
task$data
#> 'unresolved' logi NA
daemons(n = 0L)
```

**Comment by shikokuchuo** [comment]
When I run this, this is because dispatcher doesn't load. I haven't investigated why yet, but if you simply use the launcher, e.g.:

```r
```

**Comment by wlandau** [comment]
True, yes, my original error happened because `socket` was not an argument of the function I passed to `callr`. But I am having trouble with tasks failing to complete, as well as random crashes, on my local macbook. Tough to reproduce.

**Comment by shikokuchuo** [comment]
Try [8c77acb](https://github.com/shikokuchuo/mirai/commit/8c77acbc38fa2709879446eec8c0a6a91a7a5f72)

I reverted a session finaliser I added. I also got a weird segfault running `crew` tests - malloc() double linked lists. This is definitely R rather than NNG.

**Comment by wlandau** [comment]
Thanks for working on this. I tried that commit of `mirai`, and I am still consistently getting crashes running [this test](https://github.com/wlandau/crew/blob/b0405a26595dec1f997c3767f616c2df9c2bb6ea/tests/testthat/test-crew_launcher_local.R#L1-L88) in RStudio. When I run it in the terminal and print out the value of `daemons` [here](https://github.com/wlandau/crew/blob/b0405a26595dec1f997c3767f616c2df9c2bb6ea/tests/testthat/test-crew_launcher_local.R#L35), I always see `'errorValue' int 5 | Timed out` after multiple calls to `mirai::daemons()` that run in quick succession.

**Comment by shikokuchuo** [comment]
> When I run it in the terminal and print out the value of `daemons` [here](https://github.com/wlandau/crew/blob/b0405a26595dec1f997c3767f616c2df9c2bb6ea/tests/testthat/test-crew_launcher_local.R#L35), 

Right beneath your highlighted line, I see a reference to "status_online", which is now just "online".
Sorry for changing these around, but you might need to go through the tests to replace these.

**Comment by wlandau** [comment]
I like the new names, it's not much trouble to make the switch in `crew`. I think they are all migrated in `crew` in subsequent commits. And I hope #48 helps make more sense of the errors and crashes I am reporting.
