### ISSUE TITLE
Daemons (background processes) persist after ending R session

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/mirai#5]
It is currently documented for daemons:

> It is highly recommended to shut down daemons by setting daemons(0) or explicitly unloading the package before exiting your R session. This will ensure that all processes exit cleanly and resources are freed.

This issue is now fixed in ea68890 and any daemons at the end of an R session will be shut down properly. This will be in future CRAN releases >= 0.4.1.

In the meantime, dev versions incorporating this fix may be installed using: 
`install.packages("mirai", repos = "https://shikokuchuo.r-universe.dev")`

**Comment by VladPerervenko** [comment]
Problem still exists

`> library(mirai)
> daemons(4)
[1] 4
> daemons("view")
[1] 4`

4 R processes start

`> daemons(0)`
4 processes stop, but the main one hangs. It was the same in the previous version.

**Comment by shikokuchuo** [comment]
Thanks for the report. From the description, this is another issue altogether. The main process ‘hanging’ likely means that it is left waiting for the exit signals from the daemon processes. As you say that the processes actually exit, that means that they exit before being able to send their exit signals.

It will be straightforward to make sure that the main process doesn’t hang at least. But the latter issue will need some investigation, possibly being platform-specific.

In any case, a fix will be issued for this.

**Comment by VladPerervenko** [comment]
Additionally. The experiment was carried out in Rstudio. Rstudio hangs and can only be reset through the task manager.
Good luck

**Comment by shikokuchuo** [comment]
This is fixed as of 2ee650f. Platform-specific to Windows.

Dev versions already incorporate this: `install.packages("mirai", repos = "https://shikokuchuo.r-universe.dev")`

The requirement for a response from the daemons was perhaps too stringent anyway, we only really need to confirm the kill signal has been successfully sent.
