### ISSUE TITLE
"'errorValue' int 7 | Object closed" with transient sockets and transient workers

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#50]
As I mentioned in https://github.com/shikokuchuo/mirai/issues/48#issuecomment-1498370595, when I work on https://github.com/wlandau/crew/issues/61 and test [crew transient workers](https://github.com/wlandau/crew/blob/61/tests/throughput/test-transient.R), I notice a lot of `"'errorValue' int 7 | Object closed"` (about 50% of tasks in that test). The following example reproduces the same issue (at least on my Ubuntu machine) with just `mirai` and `nanonext`. I think it has something to do with the fact that I am using transient single-task workers and recycling the websocket with `saisei()` after each task.

```r
library(mirai)
library(nanonext)
packageVersion("mirai")
#> [1] ‘0.8.2.9007’
packageVersion("nanonext")
#> [1] ‘0.8.1.9008’
daemons(n = 1L, url = "ws://127.0.0.1:5000")
count <- 0L
while (TRUE) {
  count <- count + 1L
  m <- mirai("done")
  launch(
    sprintf(
      "mirai::server(url = '%s', asyncdial = FALSE)",
      saisei(i = 1L)
    )
  )
  while (unresolved(m)) {
    msleep(10)
  }
  stopifnot(identical(m$data, "done"))
}
count
#> 64
m$data
#> 'errorValue' int 7 | Object closed
daemons(n = 0L)
```

**Comment by wlandau** [comment]
On my Macbook, I see `'errorValue' int 7 | Object closed` as soon as `count == 2`.

**Comment by shikokuchuo** [comment]
You are getting those errors because you are using `saisei()` improperly. If the socket is closed while a mirai is ongoing then it will return 7 Object closed.

`saisei()` should only be called if there is no existing connection at the socket, otherwise you will risk losing mirai tasks. I have added in this safeguard in [c351fc6](https://github.com/shikokuchuo/mirai/commit/c351fc647bd5e5a2866345eef80ddd2bcba022b1).

I am sure this ties in with your needs as well. The above example just runs indefinitely now as `saisei()` has no effect.

**Comment by wlandau** [comment]
Thanks for the safeguard! In my case, I cannot ignore the possibility that a worker suddenly connects between the time I check it and the time I try to rotate the path, so this is really helpful.

Things on my end are working slightly better, although I am noticing a rare race condition where `crew` sometimes loses tasks, and I still see frequent instances of `'errorValue' int 7 | Object closed` in the [transient worker throughput test](https://github.com/wlandau/crew/blob/61/tests/throughput/test-transient.R).

**Comment by wlandau** [comment]
This test does not call `saisei()` at all, and every so often, the task is lost even though the worker is running. I am having trouble reproducing it without `crew`.

```r
library(crew)
x <- crew_controller_local()
x$start()
x$router$poll()
d <- x$router$daemons
x$push(command = ps::ps_pid(), name = "task_pid")
x$wait(seconds_timeout = 5)
out <- x$pop(scale = FALSE)
stopifnot(!is.null(out)) # should not be NULL
x$terminate()
```

**Comment by shikokuchuo** [comment]
You will only get 7 object closed if you close the socket at dispatcher (at the listener), as this is seen as intentional.
If the server times out, the connection is dropped, but this is detected by the listener and the task is queued for re-try.
I hope this helps.

**Comment by wlandau** [comment]
That's what I thought. 

Looking at my original reprex from the top of the thread, I forgot to add `maxtasks = 1L` to represent the case of single-task servers. The following example loses the task at `count = 2` on my Macbook:

```r
library(mirai)
library(nanonext)
packageVersion("mirai")
#> [1] ‘0.8.2.9009’
packageVersion("nanonext")
#> [1] ‘0.8.1.9008’
daemons(n = 1L, url = "ws://127.0.0.1:5000")
count <- 0L
while (TRUE) {
  count <- count + 1L
  m <- mirai("done")
  launch(
    sprintf(
      "mirai::server(url = '%s', asyncdial = FALSE, maxtasks = 1L)",
      saisei(i = 1L)
    )
  )
  start <- mclock()
  while (unresolved(m)) {
    if (mclock() - start > 5000) break # 5-second timeout, should be long enough
    msleep(1)
  }
  stopifnot(identical(m$data, "done"))
}
count
#> 2
m$data
#> 'unresolved' logi NA
daemons(n = 0L)
```

**Comment by wlandau** [comment]
I fixed a bug in my example above, and now I am getting `'errorValue' int 7 | Object closed` instead of losing the worker.

**Comment by shikokuchuo** [comment]
The loop logic needs a look, I think you mean something like:

```r
while (unresolved(m) || mclock() - start < 5000)
```
Otherwise you risk calling `saisei()` while the connection is still live and it will return NULL.

**Comment by wlandau** [comment]
Hmm... maybe that's not right either, I tried suppressing launches when the `callr` process PID is active, and that didn't seem to solve it. Something about `crew` and quick calls to `saisei()` seems off.

**Comment by shikokuchuo** [comment]
The above now works with v0.8.2.9012.
