### ISSUE TITLE
Return the PID from launch()

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#52]
As we discussed before, it would be nice if `launch()` returned the PID of the server process it launches. That way, I can replace `callr::r_bg()` with `mirai::launch()` in `crew`, which would allow me to drop a package dependency.

By the way, do you know if NNG has a replacement for `getip::getip(type = "local")`? If I could drop the `getip` package too, then `crew` would be just about as light as possible.

**Comment by shikokuchuo** [comment]
> As we discussed before, it would be nice if `launch()` returned the PID of the server process it launches. That way, I can replace `callr::r_bg()` with `mirai::launch()` in `crew`, which would allow me to drop a package dependency.

Done in 8335e57 (v0.8.2.9013) on a roll today!

> By the way, do you know if NNG has a replacement for `getip::getip(type = "local")`? If I could drop the `getip` package too, then `crew` would be just about as light as possible.

This is not in NNG. The trouble lies in catering to different platforms or I would just implement in nanonext...

**Comment by shikokuchuo** [comment]
Just a note - you will need to test the return value with `is_error_value()` as the PID is also an integer.

**Comment by wlandau** [comment]
Awesome!

> on a roll today!

Indeed you are!

This implementation of `launch()` almost works for me, the only hitch is that `crew` actually runs its own wrapper around `mirai:server()`: https://github.com/wlandau/crew/blob/main/R/crew_worker.R. It doesn't do very much now that we solved https://github.com/wlandau/crew/issues/61, but it does set environment variables that allow tasks to report which worker they ran on. Would it be possible to accept an arbitrary piece of R code in `launch()`? `crew` already creates it with the `call()` method of the launcher as shown in https://wlandau.github.io/crew/articles/launcher_plugins.html#example.

**Comment by shikokuchuo** [comment]
Actually that feels more brittle to future changes. Do I just need to add an argument `env` to map to the system2 call?

**Comment by wlandau** [comment]
Yes, just an `env` argument for `system2()` has everything I need for the extra stuff in `crew::crew_worker()`.

**Comment by shikokuchuo** [comment]
OK, done in [c3c6ac0](https://github.com/shikokuchuo/mirai/commit/c3c6ac07ec71d0ecfcf6205a8d988779e3c5db6c). v0.8.2.9014.

**Comment by shikokuchuo** [comment]
Launch is currently synchronous i.e. waits for the PID to be received. I think it would be better to do an asynchronous receive. Then the recvAio will resolve to the PID or a timeout error after 2s.

**Comment by wlandau** [comment]
> OK, done in [c3c6ac0](https://github.com/shikokuchuo/mirai/commit/c3c6ac07ec71d0ecfcf6205a8d988779e3c5db6c). v0.8.2.9014.

Thanks! I have updated `crew` to use `mirai::launch()` instead of `callr::r_bg()`. This eliminates the dependency on `callr` (although `processx` is still a `Suggests:` package for testing and vignettes).

> Actually synchronous is cleaner if you can live with it. Async poses the question of disposing of the socket once done etc.

Synchronous is totally fine. I think anyone who uses it in `targets` pipelines will want persistent workers anyway, so a little bit of blocking startup time is not an issue.

**Comment by wlandau** [comment]
Hmmm... somehow I missed this from the `system2()` documentation:

> On Windows, env is only supported for commands such as R and make which accept environment variables on their command line.

Indeed, when I set `env` in `launch()` on Windows, I get `'errorValue' int 5 | Timed out`.

As a stopgap for now, I plan to revert `crew` to directly call `processx` (I don't think I need all of `callr`). I already use `processx` for vignettes and testing, and even a little bit of robustness is worth the extra package dependency. In the meantime, if you happen to find another way to integrate `launch()`, please let me know.

**Comment by shikokuchuo** [comment]
Can we just use R instead of Rscript then for Windows?

**Comment by wlandau** [comment]
Would that help? Are you thinking about an alternative to `system2()`? Sorry, I don't think I follow entirely.

**Comment by wlandau** [comment]
> In the meantime, if you happen to find another way to integrate launch(), please let me know.

On reflection, I actually think I prefer `processx` regardless. During the process of coding with `mirai::launch()`, I noticed  `ps::ps_kill()` throws an error if the process already exited. I ended up wrapping it in `try()`, but that does not seem very clean. The `processx` `kill()` method is silent if the process already terminated, which seems cleaner and worth the dependency on `processx`. Sorry I did not realize this before, it could have saved you some work.

**Comment by shikokuchuo** [comment]
Well the documentation explicitly says it is supported for R, so let's call R on Windows.

Do you mind trying mirai 0.8.2.9017 on Windows regardless of what you decide? I really want to know if there is a fundamental reason it won't work. Thanks!

**Comment by shikokuchuo** [comment]
> > In the meantime, if you happen to find another way to integrate launch(), please let me know.
> 
> On reflection, I actually think I prefer `processx` regardless. During the process of coding with `mirai::launch()`, I noticed `ps::ps_kill()` throws an error if the process already exited. I ended up wrapping it in `try()`, but that does not seem very clean. The `processx` `kill()` method is silent if the process already terminated, which seems a bit more robust and worth the dependency on `processx`. Sorry I did not realize this before, it could have saved you some work.

I was always under the impression that `callr` was a wrapper of `processx`, which was a wrapper of `ps`... 
Just had a quick look at the processx code (just the R side) - tons of calling handlers...

**Comment by wlandau** [comment]
Sounds like a plan!
