### ISSUE TITLE
Typo in ?daemons

### ISSUE THREAD

**Issue by HenrikBengtsson** [shikokuchuo/mirai#57]
Should "2 remote servers" in:

https://github.com/shikokuchuo/mirai/blob/3999904054e7fbebad087609c5389e56a56ab64a/R/mirai.R#L663-L664

be "2 remote daemons"?

**Comment by shikokuchuo** [comment]
Thanks @HenrikBengtsson yes I guess it does read better as 'daemons'. Changed as part of [a1c32cb](https://github.com/shikokuchuo/mirai/commit/a1c32cbe981176a9a17ea3887e7d1cda2a1b8480).
