### ISSUE TITLE
Load-testing with TLS on MacOS

### ISSUE THREAD

**Issue by shikokuchuo** [shikokuchuo/mirai#65]
Sporadic hangs seen in #64 (fixed) persist on MacOS under extreme load-testing, only for TLS (wss). It has been noted this may not present in more realistic usage.

To investigate why this platform behaves differently.

**Comment by shikokuchuo** [comment]
To summarize, this is manifestly different to #64 as there is no deadlock and crash at dispatcher.

Testing on Intel MacOS, 2 or 3 tasks are not returned in 60,000 runs. This doesn't actually cause anything to hang, the test loop just keeps waiting for them. These processes appear to have exited, but still show as online at dispatcher. Dispatcher exits correctly and with it connected daemons.

**Comment by shikokuchuo** [comment]
It turns out this is an issue with using callr/processx to launch the daemon processes. I remember reading an issue re. processes exiting too quickly for the status to be registered or something to that effect, but can't seem to find it again.

Replacing callr with the all refreshed native `launch()` function in mirai eliminates this issue altogether. Not to mention speeding it up immensely. Updated code at: https://github.com/shikokuchuo/wip/blob/main/mirai_tls_load_test.R

I can't really say what the interaction is that triggers this, but suffice to say that real usage cases for TLS would not involve the local launcher in {crew}.

Incidentally, I have also tested locally on Windows just to see how the other major platform is doing, and it works surprisingly well, also no problems! I say 'surprisingly' given how difficult it is to test that platform on CI!

**Comment by wlandau** [comment]
Hmm.... it appears that at least on my end, the `system2()` launcher does not solve the hanging I observe on Mac OS in https://github.com/wlandau/crew/blob/main/tests/throughput/test-backlog-tasks_max.R (with TLS enabled). It's strange, given how well https://github.com/shikokuchuo/wip/blob/main/mirai_tls_load_test.R works and how similar `crew_worker()` is to `mirai::launch_local()`

**Comment by wlandau** [comment]
Looking back at TLS on Mac OS, I realized your load test at https://github.com/shikokuchuo/wip/blob/main/mirai_tls_load_test.R implicitly sets [`maxtasks = Inf`](https://github.com/shikokuchuo/wip/blob/64ba6f6c5f5397fae2f97ab947850beaae728c4a/mirai_tls_load_test.R#L74):

```r
workers$workers$handle[[index]] <- {launch(workers$workers$socket[index]); 1L}
```

I think this is why your original load test runs fine and mine hangs. Beginning with your load test, I updated `maxtasks = 100L` and switched `launch()` to `launch_local()`:

```r
workers$workers$handle[[index]] <- {
  launch_local(
    url = workers$workers$socket[index],
    maxtasks = 100L
  )
  1L
}
```

and I immediately saw hanging when I ran the test. So I think I have eliminated `processx` and `callr` as possible explanations. After that, the additional layer is `crew::crew_schedule()`, and that's just a simple queue for bookkeeping aio objects (shouldn't cause a problem).

Here is the updated code:

```r
library(crew)
library(mirai)

# Implements throttling to avoid overburdening the {mirai} dispatcher.
throttler <- crew::crew_schedule()

# Efficient and convenient data structure to keep track of {mirai} tasks.
schedule <- crew::crew_schedule()
schedule$start()

# Start the {mirai} client.
n <- 20L
mirai::daemons(
  n = n,
  url = "wss://127.0.0.1:5555",
  dispatcher = TRUE,
  token = TRUE
)

# Mutable structure with {crew} worker info. This is the primary
# data structure of each {crew} launcher.
workers <- new.env(parent = emptyenv()) # For mutability.
workers$workers <- tibble::tibble(
  handle = replicate(n, new.env(), simplify = FALSE), # callr::r_bg() handles
  socket = environment(mirai::daemons)$..$default$urls, # starting URLs
  launches = rep(0L, n), # number of times a worker was launched at this index
  launched = rep(FALSE, n), # FALSE if the worker is definitely done.
  assigned = rep(0L, n), # Cumulative "assigned" stat to check backlog (#79).
  complete = rep(0L, n) # Cumulative "complete" stat to check backlog (#79).
)

# For {mirai} servers with online == 0L and instance == 1L,
# rotate the websocket URL. Also set workers$launched to FALSE,
# which signals that tally() can safely update the cumulative
# "assigned" and "complete" statistics (#79).
rotate <- function(workers) {
  info <- mirai::status()$daemons
  done <- which(info[, "online"] < 1L & info[, "instance"] > 0L)
  for (index in done) {
    socket <- mirai::saisei(i = index, force = FALSE)
    if (!is.null(socket)) {
      workers$workers$socket[index] <- socket # Next launch is at this URL.
      workers$workers$launched[index] <- FALSE # Lets tally() update stats.
    }
  }
}

# For workers that are definitely done and not going to dial in until the
# next launch, update the cumulative "assigned" and "complete" which {crew}
# uses to detect backlogged workers (#79). A backlogged worker is a {mirai}
# server with more assigned than complete tasks. Detecting the backlog
# is important because if a worker is disconnected and backlogged,
# then {crew} will need to relaunch it so the backlogged tasks can run.
tally <- function(workers) {
  info <- mirai::status()$daemons
  index <- !(workers$workers$launched) # Workers safe to update.
  workers$workers$assigned[index] <- as.integer(info[index, "assigned"])
  workers$workers$complete[index] <- as.integer(info[index, "complete"])
  invisible()
}

# In {crew}, the scale() method of the launcher class
# re-launches all backlogged non-launched workers,
# and then it may launch additional non-launched workers
# in order to meet the demand of the task load.
# The scale() function below is a simplified version which launches
# all non-launched workers.
scale <- function(workers) {
  for (index in which(!workers$workers$launched)) { # non-launched workers
    # I would have used mirai::launch_server() here, but callr::r_bg()
    # allows me to manually terminate the server without calling
    # mirai::daemons(n = 0L). This is important for updating the final
    # assigned and complete tallies later on.
    workers$workers$handle[[index]] <- callr::r_bg(
      func = function(url, tls) {
        mirai::daemon(
          url = url,
          tls = tls,
          maxtasks = 100L
        )
      },
      args = list(
        url = workers$workers$socket[index],
        tls = nanonext::weakref_value(
          environment(mirai::daemons)$..$default$tls
        )
      )
    )
    # Increment the launch count.
    workers$workers$launches[index] <- workers$workers$launches[index] + 1L
    # Signal to tally() to wait for this worker to complete
    # instead of updating the cumulative assigned and complete stats.
    workers$workers$launched[index] <- TRUE
  }
}

index <- 0L # current task
n_tasks <- 60000L # all tasks
results <- list()
while (index < n_tasks || schedule$nonempty()) { # while there is work to do
  if (!throttler$throttle()) { # avoid overburdening the {mirai} dispatcher
    rotate(workers) # Rotate the URLs of done workers.
    tally(workers) # Update the cumulative stats for done workers.
    scale(workers) # Re-launch all the done workers.
  }
  # If there are still tasks to launch, launch one.
  if (index < n_tasks) {
    index <- index + 1L
    cat("push", index, "\n")
    task <- mirai(index, index = index)
    # The "schedule" is nothing fancy for the purposes of #88 and #89,
    # it is just a fast data structure for bookkeeping {mirai} objects
    # without the other frills in {crew}.
    schedule$push(task)
  }
  # Try to process the results of finished tasks.
  if (schedule$nonempty()) { # If there are still tasks to process...
    # Call nanonext::.unresolved() and move resolved tasks
    # from the hash table in schedule$pushed to the first-in/first-out
    # linked list in schedule$collected.
    schedule$collect()
    task <- schedule$pop() # Return a task that was resolved and collected.
    # pop() returns NULL if there is no resolved/collected task.
    if (!is.null(task)) {
      data <- task$data
      results[[data]] <- data
      cat("pop", data, "\n")
    }
  }
}

# Terminate the dispatcher.
daemons(n = 0L)

# Check the results.
all(sort(as.integer(unlist(results))) == seq_len(n_tasks))
```

**Comment by wlandau** [comment]
Actually, sometimes there is no hanging, but other times there are still one or two dangling `daemon()` processes and a segfault when I restart my local session.

**Comment by shikokuchuo** [comment]
Interesting. I can confirm that the updated code runs fine under Linux.

As this is confined to MacOS on local launchers where using TLS is not meaningful, *and* under unrealistic test conditions, I am not pursuing this further, unless a commercial need arises.

**Comment by wlandau** [comment]
That's fair. Now we know where to resume if needed.

**Comment by shikokuchuo** [comment]
Adding a reference that this is now solved according to: https://github.com/shikokuchuo/mirai/discussions/63#discussioncomment-7062657
