### ISSUE TITLE
Reliable segfault in a simple example

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#67]
While debugging https://github.com/wlandau/crew/issues/104, I isolated a simple `mirai`-only example of an issue that I have been seeing for months. When I run the R code below, my local RStudio session crashes when I restart the local R session, and the `mirai` dispatcher keeps running indefinitely. I think it may have something to do with tasks that never got a chance to dispatch. In this situation, I would expect to avoid a local crash, and I would expect the dispatcher to close when the host session closes/restarts.

```r
mirai::daemons(n = 1L, url = "ws://127.0.0.1:5004", dispatcher = TRUE, token = FALSE)
tasks <- replicate(2L, mirai::mirai(TRUE))
Sys.sleep(1)
rstudioapi::restartSession() # crashes RStudio
```

The good news is:

1. The crash and the zombie dispatcher happen every time I run the example. (Often when I am debugging issues like these, the cause is elusive because the error happens so infrequently and unpredictably, but this time was much easier!)
2. On my end, all other instances of zombie dispatchers and "error 5" timeouts have vanished thanks to https://github.com/shikokuchuo/mirai/commit/3f15eadc04045252d501772d519c54cecc583f0a, so upgrading to req/rep was a great move!

**Comment by wlandau** [comment]
> On my end, all other instances of zombie dispatchers and "error 5" timeouts have vanished thanks to https://github.com/shikokuchuo/mirai/commit/3f15eadc04045252d501772d519c54cecc583f0a, so upgrading to req/rep was a great move!

Indeed a great move, but a minute ago I just hit another "error 5" timeout on my local Ubuntu machine while running `cover::package_coverage()`. Still elusive, but the fact that it almost never happens is really nice.

**Comment by shikokuchuo** [comment]
This may happen *only after* the session has been closed. So this is not nice, but importantly does not result in any data loss etc. Indeed ending the session prematurely causes the crash (and not the other way round!). Dispatcher not exiting is not ideal though, so this will be fixed.

**Comment by wlandau** [comment]
Thanks @shikokuchuo! Works great on my end. And I'm glad it turned out to be a quick one-line patch.
