### ISSUE TITLE
Import parallel?

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#73]
Regarding this line:

https://github.com/shikokuchuo/mirai/blob/d6b1cfafc0460ae57a17fdaba6ece35182d5d52f/R/mirai.R#L1381

`nextRNGStream()` is a function from `parallel`.

**Comment by shikokuchuo** [comment]
Imported here: https://github.com/shikokuchuo/mirai/blob/282465ba27ab1b6f39c83aae7acd45e3eab8fe4d/R/mirai-package.R#L56

As far as I'm aware it is a matter of taste whether base packages are listed in DESCRIPTION (as all R installations include them).
