### ISSUE TITLE
segfault in Rscript

### ISSUE THREAD

**Issue by ElianHugh** [shikokuchuo/mirai#9]
Hi there! I've been trying to test out mirai non-interactively but have been running into a segfault about memory mapping 

I can reproduce this error pretty handidly:
```
Rscript -e "library(mirai); x <- mirai ({1}); print(x)"
```

---
As an aside, I just wanted to say thanks for expanding the support for async capabilities in R.

**Comment by shikokuchuo** [comment]
Thanks for the minimal reprex that really gets at the heart of the issue! This is essentially due to the R instance being reaped faster than the mirai can return. The R commands are already finished but there are ongoing (async) operations at the C level. The simple way to avoid this is to prolong the R instance. The below is sufficient for me:
```
Rscript -e "library(mirai); x <- mirai ({1}); print(x); Sys.sleep(0.5)"
```
The design of mirai assumes that the `mirai()` call is made from a at least somewhat long-running instance, with the mirai tasks being more ephemeral. Obviously you've found a new way to use mirai, which is great.

If you think this merits some sort of guard in mirai do let me know more about your use case, but there isn't a trivial, cost-free way to implement this off the top of my head.

**Comment by ElianHugh** [comment]
> Thanks for the minimal reprex that really gets at the heart of the issue! This is essentially due to the R instance being reaped faster than the mirai can return. The R commands are already finished but there are ongoing (async) operations at the C level. The simple way to avoid this is to prolong the R instance. The below is sufficient for me:
> ```
> Rscript -e "library(mirai); x <- mirai ({1}); print(x); Sys.sleep(0.5)"
> ```
> The design of mirai assumes that the `mirai()` call is made from a at least somewhat long-running instance, with the mirai tasks being more ephemeral. Obviously you've found a new way to use mirai, which is great.
> 
> If you think this merits some sort of guard in mirai do let me know more about your use case, but there isn't a trivial, cost-free way to implement this off the top of my head.

Thank you for the quick response! The sys.sleep fix worked for me too. 

Mostly I was interested in asynchronous R code that can be called non-interactively, and will resolve without early exit (i.e. Rscript closing before async calls finish).

Background: I've been developing an io streaming package with later as the async framework, but have the issue where streaming doesn't work because of the aforementioned early exit issue. I've found ways around this but was interested if alternative implementations ran into this issue or not :)

**Comment by shikokuchuo** [comment]
Interesting. Just a note that both nanonext and mirai are primarily designed with non-interactive 'production' use in mind. Just typically you'd expect something to happen after getting the return value from the mirai, i.e. it forms part of a longer script, and hence you wouldn't likely come across this particular issue.

I am guessing as you are developing a package, you are looking for it to perform some atomic purpose and are hence running into this.

I am not sure what forms of io you mean, but as you mention streaming, I thought it might be worth drawing your attention to `stream()` in {nanonext} (which implements the low level stream interface of NNG). Once created, this allows async send and receive over a bytestream, assuming your source is available as a socket connection.

**Comment by shikokuchuo** [comment]
It just occurred to me what you are actually looking for is:
```
Rscript -e "library(mirai); x <- mirai ({1}); print(call_mirai(x))"
```
If you call the mirai, this will wait for resolution and is hence guaranteed to return correctly.

**Comment by shikokuchuo** [comment]
Am closing as I don't think there is anything further to be done for now. If you come across anything useful do let me know, thanks.
